mavensmate/TrainingClass/src/objects/Training_Class__c.object
<CustomObject>
    <label>Training Class</label>
    <nameField>
        <label>Training Class Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mavensmate/TrainingClass/src/objects/Training_Participants__c.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <length>48</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Training  Classes</relationshipLabel>
        <relationshipName>Training_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Class__c</fullName>
        <label>Training Class</label>
        <referenceTo>Training_Class__c</referenceTo>
        <relationshipLabel>Training Participants</relationshipLabel>
        <relationshipName>Training_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Training_Role__c</fullName>
        <label>Training Role</label>
        <picklist>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trainee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trainer</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Training Participants</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Participant Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:17:13/unpackaged/classes/TrainingParticipantExt.cls
public with sharing class TrainingParticipantExt {

    private Apexpages.StandardController sController;
    private Training_Participants__c trainingParticipants;
    //private Training_Participants__c editTrainingParticipant;
    private String queryString;
    public String trainingRole{get;set;}

 
    public TrainingParticipantExt(ApexPages.StandardController controller) {
        sController = controller;
        this.trainingParticipants = (Training_Participants__c)sController.getRecord();
        List<String> pageUrl = ApexPages.currentPage().getUrl().split('\\?');
        queryString = pageUrl[1]; 
        trainingRole = 'Trainee';  // this is the default radio button selection
    }

    public List<SelectOption> getRole(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Instructor', 'Instructor'));
        options.add(new SelectOption('Trainer', 'Trainer'));
        options.add(new SelectOption('Trainee', 'Trainee'));
        return options;
    }

    public Pagereference doSaveAndNew(){
      try{
        trainingParticipants.Training_Role__c = trainingRole;
        upsert trainingParticipants;
        //Get the Meta Data for Training_Participants__c
        Schema.DescribeSObjectResult describeResult = sController.getRecord().getSObjectType().getDescribe();
        //Create pageReference for creating a new sObject and add any inbound query string parameters
        PageReference pr = new PageReference('/'+describeResult.getKeyPrefix()+'/e?' + queryString);
        //Don't redirect with the viewstate of the current record
        pr.setRedirect(true);
        return pr;
      } catch(Exception e){
        ApexPages.addMessages(e);
        return null;
      }
    }

    public PageReference doSave(){
        trainingParticipants.Training_Role__c = trainingRole;
         if(trainingRole=='Trainee'){
            trainingParticipants.Trainer__c =null;
        }else{
             trainingParticipants.Participant__c='';   
        }
        upsert trainingParticipants;
        return new PageReference('/'+trainingParticipants.Training_Class__c);

    }

    public PageReference doCancel(){
        return sController.cancel();
    }

}