mavensmate/Project Project/src/objects/Project_Module__c.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Large__c</fullName>
        <label>Large</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Medium__c</fullName>
        <label>Medium</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Module_Type__c</fullName>
        <label>Module Type</label>
        <picklist>
            <picklistValues>
                <fullName>Inspection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Rail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip Line</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project Modules</relationshipLabel>
        <relationshipName>Project_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Small__c</fullName>
        <label>Small</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Type</label>
    <nameField>
        <label>Project Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Project Project/src/classes/ProjectModuleExt.cls
public with sharing class ProjectModuleExt {

    
    Apexpages.StandardController stdController;

    public ProjectModuleExt(ApexPages.StandardController stdController) {
        this.stdController = stdController;
     
    }

    public PageReference doCancel(){
        Project_Module__c m = (Project_Module__c)stdController.getRecord();
        PageReference pageRef = new PageReference('/' + m.Opportunity__c);
         return pageRef;
        //return stdController.cancel();
    }


    public PageReference doSave(){
        Project_Module__c m = (Project_Module__c)stdController.getRecord();
        PageReference pageRef = new PageReference('/' + m.Opportunity__c);
        m.Name = m.Module_Type__c;
        stdController.save();
        return pageRef;
        //return stdController.cancel();
    }
 
    /*
    ApexPages.standardController m_sc = null;

    public ProjectModuleExt(ApexPages.standardController sc){
         m_sc = sc;
    }

     public PageReference doCancel() {
        PageReference pageRef = new PageReference('/' + m_sc[0].Opportunity__c);
        return pageRef;
        //return m_sc.cancel();
     }
*/
     /*
PageReference pageRef = new PageReference('/' + oppMetrics[0].Opportunity__c);
return pageRef;
     */

     /*
    public PageReference save() {
         Project_Module__c m = (Project_Module__c)stdController.getRecord();
         m.Name = m.Module_Type__c;

         //set default values here if they are null?
         if(m.Small__c==null){m.Small__c=0;}
         if(m.Medium__c==null){m.Medium__c=0;}
         if(m.Large__c==null){m.Large__c=0;}
         if(m.Capacity__c==null){m.Capacity__c=0;}

        return stdController.save();     
    }   
 */
}