mavensmate/Google Maps/src/objects/Course_Detail__c.object
<CustomObject>
    <description>Specs for courses owned by customers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Course_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>Auto Zip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouldering Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTS Zipline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Low Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability High Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Navigator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Explorer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Voyager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Expedition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Tykes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Endeavor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track-n-Trail Steel Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teams Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Ropes Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dangle Duo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pamper Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Instructor Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical Playpen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Self Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portable Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burma Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk an I-Beam</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Safety Equipment/src/objects/Safety_Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Safety Equipment</relationshipLabel>
        <relationshipName>Safety_Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>RSA2 Slingline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trolley Slingline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skyrail Slingline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_Serial_Number__c</fullName>
        <label>Start Serial Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Safety Equipment</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safety Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mavensmate/Project Project/src/classes/TestConfiguration.cls
@isTest
public with sharing class TestConfiguration {
	
	public static List<Account> createAccounts(String baseName, Integer count){		
		List<Account> results = new List<Account>();		
		for(Integer a = 0; a<count; a++){
			results.add(new Account(Name = baseName + String.valueOf(a)));
		}
		return results;
	}
	
	public static List<Contact> createContacts(String baseName, Integer count, List<Account> accounts){
		List<Contact> contacts= new List<Contact>();		
		for(Account a: accounts){			
			for(Integer c=0; c<count; c++){
				contacts.add(new Contact(LastName=baseName + String.valueOf(c), AccountId=a.Id));
			}
		}		
		return contacts;
	}
	
	public static List<Certification__c> createCertifications(String baseName, Integer count, List<Contact> contacts, Date certificationDate){
		List<Certification__c> certifications = new List<Certification__c>();
		for(Contact c: contacts){
			for(Integer i = 0; i<count; i++){
				certifications.add(new Certification__c(Contact__c=c.Id, Certification_Date__c=certificationDate));
			}
		}
		return certifications;
	}
	
	public static List<Opportunity> createOpportunities(String baseName, Integer count, List<Account> accounts, String stageName){
		List<Opportunity> opportunities= new List<Opportunity>();		
		for(Account a: accounts){			
			for(Integer c=0; c<count; c++){
				opportunities.add(new Opportunity(Name=baseName + String.valueOf(c), AccountId=a.Id, StageName=stageName, CloseDate=Date.today().addDays(10)));
			}
		}		
		return opportunities;
	}
	
	
	//Loop through Accounts
	//Loop through Opportunities
	//Loop through Contacts
	//Create OpportunityContactRole for each contact for the opportunity
	public static List<OpportunityContactRole> createOpportunityContactRoles(String baseName, Integer count, List<Account> accounts, List<Opportunity> opportunities, List<Contact> contacts){
		List<OpportunityContactRole> opportunityContactRoles= new List<OpportunityContactRole>();
		
		for(Account a: accounts){		
			for(Opportunity o: opportunities){
				for(Contact c: contacts){				
							opportunityContactRoles.add(new OpportunityContactRole(Role=baseName, ContactId=c.Id, OpportunityId = o.Id));
				}
			}
		}		
		return opportunityContactRoles;
	}
	
	public static List<Course_Detail__c> createCourses(String baseName, Integer count, List<Account> accounts){
		List<Course_Detail__c> courses = new List<Course_Detail__c>();
		for(Account account: accounts){
			for(Integer c=0; c<count; c++){
				courses.add(new Course_Detail__c(Name=baseName + String.valueOf(c),Account__c=account.Id ));
			}
		}		
		return courses;
	}
	
	public static List<Course_Inspection__c> createInspections(String baseName, Integer count, List<Course_Detail__c> courses){
		List<Course_Inspection__c> inspections = new List<Course_Inspection__c>();		
		for(Course_Detail__c course: courses){
				for(Integer c=0; c<count; c++){
					inspections.add(new Course_Inspection__c(Name=baseName + String.valueOf(c), Course__c = course.Id));  
				}			
			}
		return inspections;
	}

	public static List<Safety_Equipment__c> createSafetyEquipmentInventory(Integer startSerialNumber, String status, String model,Integer count){
		List<Safety_Equipment__c> safetyEquipment = new List<Safety_Equipment__c>();

		for(Integer s = 0; s<count; s++){
			safetyEquipment.add(new Safety_Equipment__c(Serial_Number__c = startSerialNumber+s, Model__c = model, Status__c = status));
		}

		return safetyEquipment;
	}

	public static List<Safety_Equipment__c> assignSafetyEquipment(Integer startSerialNumber, Integer count, List<Account> accounts){
		List<Safety_Equipment__c> safety = new List<Safety_Equipment__c>();		
		for(Account a: accounts){			
			for(Integer c=0; c<count; c++){
				safety.add(new Safety_Equipment__c(Start_Serial_Number__c = startSerialNumber+c, Account__c=a.Id));
			}
		}		
		return safety;
	}

}