mavensmate/Google Maps/src/objects/Course_Detail__c.object
<CustomObject>
    <description>Specs for courses owned by customers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Course_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <label>Parent</label>
        <picklist>
            <picklistValues>
                <fullName>RCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovative Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faszinatour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ride Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Play</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>Auto Zip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouldering Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTS Zipline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Low Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability High Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Navigator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Explorer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Voyager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Expedition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Tykes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Endeavor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track-n-Trail Steel Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teams Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Ropes Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dangle Duo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pamper Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Instructor Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical Playpen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Self Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portable Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burma Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk an I-Beam</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year_Built__c</fullName>
        <label>Year Built</label>
        <picklist>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/SandBox/src/classes/mapController.cls
public class mapController {

   public String addrStr;
   public String AddrArStr;
   public User usr;
   public String myKey;
   Account[] accts;  
  
   Course_Detail__c[] courses;
   String courseStr;
   
   public Course_Detail__c[] getOpenCourses(){
   	courses = [SELECT Id, Name, Account__r.Name, Distributor__c, Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, Account__r.ShippingCountry, Model__c, Year_Built__c, Status__c 
   				FROM Course_Detail__c 
   				WHERE Status__c='Open'];
   				/*
   				for(Course_Detail__c course:courses){
   					
   					courseStr = courseStr + course.Account__r.Name + ' : ' +
   					course.Model__c+ ':'+
   					course.Year_Built__c+ '~:~' +
   					course.Account__r.BillingStreet + '~:~' +
   					course.Account__r.BillingCity + '~:~' +
   					course.Account__r.BillingState + '~:~' +
   					course.Account__r.BillingPostalCode + '~:~' +   			
   					course.Id + '~:~' +
   					course.Distributor__c + '~::~';
   					
   					System.debug('The courseStr : ' + courseStr);
   				}
   				*/
   		return courses;
   }


   public Account[] getMyAccts() {
      					String usrId = UserInfo.getUserId();
      					accts = [Select Id, Name, Rating, Customer_Priority__c, 
                         OwnerId, BillingStreet, BillingCity, BillingState, 
                         BillingPostalCode, BillingCountry
                         From Account 
                         where Type = 'Current Customer'
                         And OwnerId =: usrId ];
                           
      			for(Account acct : accts) {   
      	     
         			addrStr = addrStr + acct.Name + ' : ' 
                   + acct.Customer_Priority__c  + ':' 
                   + acct.Id + '~:~'+ acct.BillingStreet + '~:~' 
                   + acct.BillingCity + '~:~' +  acct.BillingState + '~:~' 
                   + acct.BillingPostalCode + '~::~';                   
                    	
            
      		}

      return accts;     
   }

   public String getmyKey() {  // Set up google maps api key     
      myKey = 'http://maps.google.com/maps?file=api&v=2.55&';
      // In the following line, enter your google maps key     
      // to get an api key, visit the Google Maps API site     
      // http://code.google.com/apis/maps/signup.html     
      myKey = myKey + 'AIzaSyA1NjbhAwdfru4t1-Yyadg6967WvjCAsRo';     
      return myKey;
   }
   
   
   public String getCourseStr(){
   		courseStr='';
   		Course_Detail__c [] theCourses = getOpenCourses();
   		
   		for(Course_Detail__c course:courses){
   			courseStr = courseStr + course.Account__r.Name + ' : ' +
   			course.Model__c+ ':'+
   			course.Year_Built__c+ ':' +
   			course.Distributor__c + '~:~' +   			
   			course.Account__r.ShippingStreet + '~:~' +
   			course.Account__r.ShippingCity + '~:~' +
   			course.Account__r.ShippingState + '~:~' +
   			course.Account__r.ShippingPostalCode + '~:~' +   			
   			course.Id + '~:~' +      			
   			course.Account__r.ShippingCountry+ '~::~';
     		}
   		return courseStr;   	
   }
 /*  
   public String getAddrArStr(){
      addrStr = '';
      Account[] theRecs = getMyAccts();      
      for(Account acct : accts) {         				
      	     
         			addrStr = addrStr + acct.Name + ' : ' 
                   + acct.Customer_Priority__c  + ':' 
                   + acct.Id + '~:~'+ acct.BillingStreet + '~:~' 
                   + acct.BillingCity + '~:~' +  acct.BillingState + '~:~' 
                   + acct.BillingPostalCode + '~::~';	            
      		}
	
      return addrStr;	
   }
*/
}