mavensmate/Google Maps/src/objects/Course_Detail__c.object
<CustomObject>
    <description>Specs for courses owned by customers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Course_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>Auto Zip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouldering Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTS Zipline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Low Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability High Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Navigator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Explorer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Voyager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Expedition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Tykes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Endeavor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track-n-Trail Steel Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teams Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Ropes Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dangle Duo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pamper Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Instructor Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical Playpen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Self Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portable Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burma Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk an I-Beam</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Built__c</fullName>
        <label>Year Built</label>
        <picklist>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/FirstMate/src/classes/ProjectController.cls
public with sharing class ProjectController {
	
	private Customer_Project__c project;
	private ApexPages.StandardController extendedController {get;set;}
	private Boolean bUpdate = true;
	public string accountId{    get;set;    }
    public string accountName{    get;set;    }
    public string oppId{    get;set;    }
    public string oppName{    get;set;    }
    public List<Opportunity> opp;
    public List<Account> account;
    public double revenue{    get;set;    }
   
	public ProjectController(ApexPages.StandardController stdController){			
		  extendedController = stdController;
          this.project= (Customer_Project__c)extendedController.getRecord();
  
  		//if the project id is null then we are creating a new record and want to pass a view values along
           accountId = System.currentPageReference().getParameters().get('accountId'); 
          if(project.id==null){
          	   accountId = System.currentPageReference().getParameters().get('accountId'); 	                  
	           account = [select Name from Account where Id =: accountId];
	           oppId = System.currentPageReference().getParameters().get('oppId');
	           opp = [select Id, Name from Opportunity where Id =: oppId];
	           revenue = [select ExpectedRevenue from Opportunity where Id =: oppId].ExpectedRevenue;
	           project.Revenue__c=revenue;
	           project.Opportunity__c = opp[0].Id;
	           project.Account__c = account[0].Id;          
          }else{
          		accountId = project.Account__c;
          }
	}
	
	public  List<Course_Detail__c> getCourses(){
		return [select Account__c, Year_Built__c, Model__c, Serial_Number__c from Course_Detail__c where Account__r.Id=:accountId];
	}
	
	public Customer_Project__c getCustomerProject() { return project;} 
	
	
	public PageReference mySave() {	
		PageReference displayProject = Page.project;
		displayProject.setRedirect(true);
		displayProject.getParameters().put('id', project.id);	
		
		if(bUpdate){
			update project;
			return displayProject;
		}else{
			insert project;
			extendedController = new ApexPages.StandardController(project);
		}
		return displayProject;
	}
	

}