mavensmate/Google Maps/src/objects/Course_Detail__c.object
<CustomObject>
    <description>Specs for courses owned by customers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Course_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>Auto Zip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouldering Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTS Zipline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Low Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability High Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Navigator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Explorer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Voyager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Expedition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Tykes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Endeavor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track-n-Trail Steel Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teams Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Ropes Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dangle Duo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pamper Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Instructor Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical Playpen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Self Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portable Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burma Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk an I-Beam</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year_Built__c</fullName>
        <label>Year Built</label>
        <picklist>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/SandBox/src/classes/TestCourseList.cls
public with sharing class TestCourseList {
	
	public static testMethod void testMe() { 
	 	//Course_Detail__c c = new Course_Detail__c(name='Test1');
	 	//CourseWrapper cw2 = new CourseWrapper(new Course_Detail__c(name='Test1'));	
	 	//System.assertEquals(cw2.course.name,'Test1');
	 	
	 	List<Course_Detail__c> testCourses = [select Id, Account__c, Model__c, Name, Year_Built__c, Selected__c, Status__c from Course_Detail__c WHERE Status__c='Open'];
		ApexPages.StandardSetController setCon = new ApexPages.StandardSetController(testCourses);
		
	//	Account testAccountFromDb = 
    // //   [SELECT Id, Name FROM Course_Detail__c WHERE Id = 'a1aQ0000000aDnDIAU'];
    //  System.assertEquals(testAccount.Id, testAccountFromDb.Id);
  /*  
    Course_Inspection__c inspection;
		
		inspection = new Course_Inspection__c();
 				inspection.Course__c = 'a1aQ0000000aDnDIAU';
 				inspection.Name = 'Test Course 33';  //this is the course id?
 				//inspection.Course_Description__c =   'Test Course - Testt Model - 2012';
 				//inspection.Inspection_Year__c = date.today().year();
 				//inspection.Inspection_Status__c = 'Pending';
 			insert	inspection;
 			
 			Course_Inspection__c ct;
 			ct =  [SELECT  Name FROM Course_Inspection__c WHERE Name = 'Test Course 33'];
      System.assertEquals(inspection.Name, ct.Name);
 	*/		
 			

//mysetcontrollerextention ext = new mysetcontrollerextension(setcon);
	 	//cw2.add(new Course_Detail__c(name='Test2')); 
	 	
	 	//System.assertEquals(cw.add(c));
	 	//System.assertEquals(c.name,'Test1');
	 	//Course_Inspection__c i = new Course_Inspection__c();
	 	
	 	
	 	CourseWrapper cw = new CourseWrapper();
    	System.assertEquals(cw.checked,false); 
    	CourseWrapper cw2 = new CourseWrapper(new Course_Detail__c(name='Test1'));
    	System.assertEquals(cw2.course.name,'Test1');
    	System.assertEquals(cw2.checked,false); 
    	
    	CourseSelectController cs = new CourseSelectController();
    	//cs.selectedCourses = new List<Course_Detail__c>();
    	//List<Course_Detail__c> selectedCourses = new List<Course_Detail__c>();
    	
    	ApexPages.StandardSetController standardSetController;
    	standardSetController = new ApexPages.StandardSetController(Database.getQueryLocator([select Id, Account__c, Model__c, Name, Year_Built__c, Selected__c, Status__c from Course_Detail__c WHERE Status__c='Open']));
    	standardSetController.setPageNumber(1);
    	 System.assertEquals(1, standardSetController.getPageNumber());
    	// CourseSelectController cs1 = new CourseSelectController(standardSetController);
    	
    	
    	//this section is not considered testing for the CourseSelectController Class
    	 Course_Inspection__c testInspect = [SELECT  Name, Course_Description__c FROM Course_Inspection__c WHERE Course__c = 'a1aQ0000000aDnDIAU'];
    	testInspect.Course_Description__c='New Description';        
     	update testInspect;   
	 
	     // Verify that the billingState field was updated in the database.
	     Course_Inspection__c updatedInspect = [SELECT  Course_Description__c, Name FROM Course_Inspection__c WHERE Course__c = 'a1aQ0000000aDnDIAU'];
	     System.assertEquals('New Description', updatedInspect.Course_Description__c);
		//end of section not being tested because of ??
		
	
	 }

}