mavensmate/Google Maps/src/objects/Course_Detail__c.object
<CustomObject>
    <description>Specs for courses owned by customers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Course_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Google Maps/src/classes/publicMapControllerTest.cls
@isTest
private class publicMapControllerTest {
	
@isTest
   private static void testGetOpenCourses(){
    List<Course_Detail__c> control = new List<Course_detail__c>();
    Account account = new Account(Name='Customer One', Location__Latitude__s=36.3809047, Location__Longitude__s = -85.83021);
    insert account;
    control.add(new Course_Detail__c(Name='Course1', Status__c='Active', Account__c = account.id));
    control.add(new Course_Detail__c(Name='Course2', Status__c='Active', Account__c = account.id));
    insert control;
    List<Course_Detail__c> actual = publicMapController.getOpenCourses();
    System.assert(actual.size()!=2);
   } 
	
}