mavensmate/Google Maps/src/objects/Course_Detail__c.object
<CustomObject>
    <description>Specs for courses owned by customers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Course_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>Auto Zip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouldering Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTS Zipline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Low Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability High Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Navigator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Explorer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Voyager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Expedition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Tykes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sky Trail Endeavor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track-n-Trail Steel Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teams Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Ropes Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dangle Duo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pamper Pole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climbing Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Instructor Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical Playpen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Ropes Self Belay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50&apos; Skyscraper Tower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portable Sky Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burma Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk an I-Beam</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:17:13/unpackaged/classes/CourseInspectionComplete_Trigger_Test.cls
@isTest
private class CourseInspectionComplete_Trigger_Test {
	
	@isTest static void test_method_one() {

		List<Account> accounts = TestConfiguration.createAccounts('AccountName ', 1);
		insert accounts;

		List<Opportunity> opps = TestConfiguration.createOpportunities('opp Name ', 1, accounts, 'Scheduled');
		opps[0].Shipping_Delivery_Address__c = '123 Main';

		insert opps;

		List<Course_Detail__c> courses = TestConfiguration.createCourses('Course Name ', 1, accounts);		
		courses[0].Account__c = accounts[0].Id;
		courses[0].Opportunity__c = opps[0].Id;
		courses[0].Model__c = 'Explorer';
		insert courses;

		List<Course_Inspection__c> inspections = TestConfiguration.createInspections('inspection name ', 1, courses);
		inspections[0].Course__c = courses[0].Id;
		inspections[0].Inspection_Complete__c = date.today();
		inspections[0].Status__c = 'Complete';
		insert inspections;

		List<Course_Inspection__c> i = [SELECT Id, Status__c, Date_of_Next_Inspection__c, Inspection_Complete__c FROM Course_Inspection__c];
		i[0].Status__c = 'Complete';
		i[0].Inspection_Complete__c = date.today();
		upsert inspections;  //this should trip the trigger to create a new record

		System.assertEquals(i[0].Status__c, 'Complete');
		System.assertEquals(i[0].Inspection_Complete__c, date.today());
		System.assertEquals(i[0].Date_of_Next_Inspection__c,date.today()+365);

		List<Course_Inspection__c> i2 = [SELECT Id, Status__c, Date_of_Next_Inspection__c, Inspection_Complete__c FROM Course_Inspection__c];

		i2[1].Status__c = 'Complete';
		i2[1].Inspection_Complete__c = date.today();
		upsert i2;		

		System.assertEquals(i[1].Status__c, 'Next Annual');
		System.assertEquals(i[1].Date_of_Next_Inspection__c, date.today()+365);

		List<Course_Inspection__c> i3 = [SELECT Id, Status__c, Date_of_Next_Inspection__c, Inspection_Complete__c FROM Course_Inspection__c];

		System.assertEquals(i3[2].Status__c, 'Next Annual');
		System.assertEquals(i3[2].Date_of_Next_Inspection__c, date.today()+365);


	}
	
}