mavensmate/Google Maps/src/objects/Course_Detail__c.object
<CustomObject>
    <description>Specs for courses owned by customers</description>
    <fields>
        <fullName>Distributor__c</fullName>
        <label>Parent</label>
        <picklist>
            <picklistValues>
                <fullName>RCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovative Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faszinatour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ride Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prime Play</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Google Maps/src/classes/InspectionMapController_Test.cls
@isTest
private class InspectionMapController_Test {
	
	@isTest  private static void testGetCourseInspections(){
    
    List<Account> accounts = TestConfiguration.createAccounts('Account Name', 1);
    accounts[0].Location__Latitude__s = 31.82752;
    accounts[0].Location__Longitude__s = -85.83021;
    insert accounts;
    List<Course_Detail__c> courses = TestConfiguration.createCourses('Course Name', 2, accounts);
    courses[0].Distributor__c = true;
    courses[1].Distributor__c = false;
    courses[1].Status__c='Active';
    insert courses;
    List<Course_Inspection__c> inspections = TestConfiguration.createInspections('Inspection Name', 2, courses);
    inspections[0].Status__c = 'Complete';
    inspections[1].Date_of_Last_Inspection__c = Date.parse('08/13/2014');
    inspections[1].Status__c = 'Next Annual';
   insert inspections;    
   
    List<Course_Inspection__c> actualInspections = inspectionMapController.getCourseInspections();
   // System.debug('actualInspections returned: ' + actualInspections.size());
    System.assertEquals(actualInspections.size(), 0);
   }  
	
	
	
}