mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:21:05/unpackaged/objects/Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-05-14 14:45:45/unpackaged/objects/Job_Fabrication_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Job_Part__c</fullName>
        <label>Job Part</label>
        <referenceTo>Job_Part__c</referenceTo>
        <relationshipName>Job_Part_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Entry_Quantity__c</fullName>
        <label>Work Entry Quantity</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Job Fabrication Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Job Fabrication Detail Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Fabrication Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Fabrication/src/objects/Job_Part__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Parts</relationshipLabel>
        <relationshipName>Job_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Imported as the quantity of the part to be manufactured</description>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Part</label>
    <nameField>
        <label>Job Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-05-14 14:45:45/unpackaged/objects/Job_Shipping_Details__c.object
<CustomObject>
    <fields>
        <fullName>Job_Part__c</fullName>
        <label>Job Part</label>
        <referenceTo>Job_Part__c</referenceTo>
        <relationshipLabel>Job Shipping Details</relationshipLabel>
        <relationshipName>Job_Shipping_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_Loaded__c</fullName>
        <label>Number Loaded</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Shipping Details</label>
    <nameField>
        <displayFormat>Shp-{000000}</displayFormat>
        <label>Job Shipping Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Shipping Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Apex Batch/src/classes/MergeJobParts.cls
global class MergeJobParts implements Database.Batchable<sObject> {
	
	String query;
	String job;

	
	//USE THE CONSTRUCTOR TO LOOK UP GLOBAL INSTANCE VARIABLE TO CONTROL WHICH JOBS THIS RUNS AGAINST
	global MergeJobParts() {

	}

	global MergeJobParts( String jobNumber) {
		job = jobNumber;
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		query = 'SELECT Name, Id, Quantity__c FROM Job_Part__c WHERE Job__r.Name = \'' + job + '\'';
        return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Job_Part__c> scope) {
   		scope.sort();
         for(Integer i = 0; i < scope.size()-1;i++ ){
            
         	if(scope[i].Name == scope[i+1].Name){
         		
         		scope[i].Quantity__c = scope[i].Quantity__c + scope[i+1].Quantity__c;

         		//fabrication child records to merge
         		List<Job_Fabrication_Detail__c> details = [SELECT Id, Name, Work_Entry_Quantity__c, Job_Part__c from Job_Fabrication_Detail__c where Job_Part__c =: scope[i+1].Id];
         		if(details.size()>0){

	         		for(Integer a = 0; a<details.size(); a++){
	         			details[a].Job_Part__c = scope[i].Id;
	         		}
	         		update details;
         		}

         		//shipping child records to merge
         		List<Job_Shipping_Details__c> shipping = [SELECT Id, Name, Number_Loaded__c, Job_Part__c from Job_Shipping_Details__c where Job_Part__c =: scope[i+1].Id];
         		if(shipping.size()>0){
         			for(Integer b = 0; b<details.size(); b++){
	         			shipping[b].Job_Part__c = scope[i].Id;
	         		}
	         		update shipping;
         		}

         		Database.delete(scope[i+1]);
         		DataBase.emptyRecycleBin(scope[i+1]); 
         		scope.remove(i+1);
         	}
         }      
         update scope;
	}
	
	global void finish(Database.BatchableContext BC) {
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
 
		mail.setToAddresses(new String[] {'kal@ropescoursesinc.com'});
		mail.setReplyTo('kal@ropescoursesinc.com');
		mail.setSenderDisplayName('Batch Processing');
		mail.setSubject('Batch Process Completed');
		mail.setPlainTextBody('Batch Process has completed');
 
		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		
	}
}