mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:21:05/unpackaged/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:17:13/unpackaged/classes/ShippingLoadProjectExtension.cls
public with sharing class ShippingLoadProjectExtension {

	private final sObject mysObject;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public ShippingLoadProjectExtension(ApexPages.StandardController stdController) {
        this.mysObject = (sObject)stdController.getRecord();
    }

    public String getRecordName() {
        return 'Hello ' + (String)mysObject.get('name') + ' (' + (Id)mysObject.get('Id') + ')';
    }

    public List<Shipping_Load_Project__c> getShippingProjects(){
       return [SELECT Id, Name, Job__c  FROM Shipping_Load_Project__c 
                   WHERE Status__c = 'Open'];
    }

     public List<Shipping_Load_Project__c> getOpenProjects(){     

        return [SELECT Job__c FROM Shipping_Load_Project__c  WHERE Status__c = 'Open'];
     
    }
}