mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:21:05/unpackaged/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Fabrication_Quantity_Complete__c</fullName>
        <formula>Fabricated_Total_Parts__c - Fabrication_Quantity_Remaining__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fabrication Quantity Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fabrication_Quantity_Remaining__c</fullName>
        <label>Fabrication Quantity Remaining</label>
        <summarizedField>Job_Part__c.Fabrication_Quantity_Remaining__c</summarizedField>
        <summaryForeignKey>Job_Part__c.Job__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Fabrication__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fabrication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paint__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shipping</label>
        <type>Checkbox</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mavensmate/Fabrication/src/objects/Job_Part__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Imported as Part Description</description>
        <label>Description</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fabrication_Quantity_Complete__c</fullName>
        <formula>(Rollup_Weld_Quantity__c + Rollup_Fit_Quantity__c)/2</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fabrication Complete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fabrication_Quantity_Remaining__c</fullName>
        <formula>Fabrication_Quantity__c -  Fabrication_Quantity_Complete__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fabrication Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fabrication__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fabrication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Parts</relationshipLabel>
        <relationshipName>Job_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Paint_Remaining__c</fullName>
        <formula>Quantity__c  - Rollup_Paint_Complete__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Paint Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Paint__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity_To_Be_Loaded__c</fullName>
        <formula>Shipping_Quantity__c -  Rollup_Loaded_Items__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Load Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Imported as the quantity of the part to be manufactured</description>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rollup_Loaded_Items__c</fullName>
        <label>Load Complete</label>
        <summarizedField>Job_Shipping_Details__c.Number_Loaded__c</summarizedField>
        <summaryForeignKey>Job_Shipping_Details__c.Job_Part__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Rollup_Paint_Complete__c</fullName>
        <label>Paint Complete</label>
        <summarizedField>Job_Paint_Detail_del__c.Paint_Complete__c</summarizedField>
        <summaryForeignKey>Job_Paint_Detail_del__c.Job_Part__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shipping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Weight_Single_Part__c</fullName>
        <description>This is an imported value used in the calculation of the weight complete.</description>
        <label>Weight Single Part</label>
        <precision>11</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Job Part</label>
    <nameField>
        <label>Job Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/TrainingClass/src/objects/Training_Participants__c.object
<CustomObject>
    <label>Training Participants</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Participant Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Fabrication/src/classes/SelectedPartsController.cls
public with sharing class SelectedPartsController {
    /*
        k.howell 5/14/2014
        Returns child parts to the job based on checkboxes selected.  Can look at the Fabrication, Paint and Shipping records independently.
    */
      /*
        Testing requires inserting a job and parts, then querying the parts
    */

	public Job__c job;
    List<Job_Part__c> selectedParts = new List<Job_Part__c>();
    public String errorMessage {get;set;}
    public Boolean checkFabrication{get; set; }
    public Boolean checkPaint{get; set; }
    public Boolean checkShipping{get; set; }
    public Boolean checkRemainingItems{get;set;}
    public String soql;
    public String jobId;
 

    //this controller is used to pass in the job information for the testing code
    public SelectedPartsController(Job__c j){
        this.job = j;
        jobId = j.Id;
    }


    public SelectedPartsController(ApexPages.StandardController stdController) {
        this.job = (Job__c)stdController.getRecord();
        jobId = job.Id;
    }  

    public List<Job_Part__c> getSelectedParts(){
        soql='';
        soql = 'SELECT ID,Name,Quantity__c,Rollup_Paint_Complete__c,Paint_Remaining__c,Quantity_To_Be_Loaded__c,Rollup_Loaded_Items__c,Fabrication_Quantity_Complete__c,'
            +'Weight_Single_Part__c,Fabrication_Quantity_Remaining__c, Description__c,Fabrication__c,Paint__c,Shipping__c FROM Job_Part__c WHERE Job_Part__c.Job__r.Id =:jobId';

        if(checkRemainingItems==true){
            if(checkFabrication==true){soql += ' AND Fabrication__c = true AND Fabrication_Quantity_Remaining__c > 0'; }
            if(checkShipping==true){soql += ' AND Shipping__c = true AND Job_Part__c.Paint_Remaining__c > 0'; }
            if(checkPaint==true){soql += ' AND Paint__c = true AND Job_Part__c.Quantity_To_Be_Loaded__c > 0' ;}
        }else{
            if(checkFabrication==true){soql += ' AND Fabrication__c = true';}
            if(checkShipping==true){soql += ' AND Shipping__c = true';}
            if(checkPaint==true){soql += ' AND Paint__c = true';}
        }             
        soql += ' ORDER BY Name ASC';
        selectedParts = Database.query(soql);
        return selectedParts;
    }


    /*

    pass in the id of the parent record.  This is in the url when the parent record is displayed

    */

    public pageReference doNew(){
        Job_Part__c part = new Job_Part__c();
        part.Job__c = job.id;
        part.Name = 'New Part Name Here';
        insert part;
        //create a new parts object
        //add the job id and name
        //open the record in the edit mode
        PageReference pr = new PageReference('/'+part.id);
        //pr.setRedirect(true);
        return pr;

    }

   
/*
 public Pagereference doSaveAndNew(){
      try{
        //save the current object
        sController.save();
        //Get the Meta Data for Training_Participants__c
        Schema.DescribeSObjectResult describeResult = sController.getRecord().getSObjectType().getDescribe();
        //Create pageReference for creating a new sObject and add any inbound query string parameters
        PageReference pr = new PageReference('/'+describeResult.getKeyPrefix()+'/e?' + queryString);
        //Don't redirect with the viewstate of the current record
        pr.setRedirect(true);
        return pr;
      } catch(Exception e){
        ApexPages.addMessages(e);
        return null;
      }
    }

public void newContact()
    {
       if (updateContacts())
       {
          Contact cont=new Contact(FirstName=newContactFirstName, LastName=newContactLastName, AccountId=getAccount().id);
          insert cont;
         
          newContactFirstName=null;
          newContactLastName=null;
          contacts=null;
       }
    }

    */
}