mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:21:05/unpackaged/objects/Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-05-14 14:33:49/unpackaged/objects/Job_Part__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Parts</relationshipLabel>
        <relationshipName>Job_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Part</label>
    <nameField>
        <label>Job Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Safety Equipment/src/objects/Safety_Equipment__c.object
<CustomObject>
    <label>Safety Equipment</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Safety Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:17:13/unpackaged/classes/filteredJobs.cls
public with sharing class filteredJobs {

    public filteredJobs(){}
    public Job__c job;
   // public Job_Part__c selectedParts;
    List<Job_Part__c> selectedParts = new List<Job_Part__c>();

    //public SafetyEquipmentController(){}
    //public Safety_Equipment__c assign;
    public String errorMessage {get;set;}
    //List<Safety_Equipment__c> safetyList = new List<Safety_Equipment__c>();
  

 public filteredJobs(ApexPages.StandardController stdController) {
        job = (Job__c)stdController.getRecord();
  }

	//private final sObject mysObject;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    //public filteredJobs(ApexPages.StandardController stdController) {
    //    this.mysObject = (sObject)stdController.getRecord();
   // }

   // public String getRecordName() {
   //     return 'Hello ' + (String)mysObject.get('name') + ' (' + (Id)mysObject.get('Id') + ')';
   // }


  //    public MyFilter(){
  //  YourObjReference = new CustomObject__c();

  //}
  //public CustomObject__c YourObjReference{get;set;}
  //public List<CustomObject__c>  yourObjList{get;set;}
  //public void filterRecords(){
  //  yourObjList = new List<CustomObject__c>();
  //  yourObjList = [SELECT Name FROM ]CustomObject__c WHERE LookupField__c=:YourObjReference.LookupField__c];
  //}
}