mavensmate/Fabrication/deploy/kalho13@gmail.com/2014-06-05 10:21:05/unpackaged/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mavensmate/Fabrication/src/objects/Job_Part__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Parts</relationshipLabel>
        <relationshipName>Job_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Part</label>
    <nameField>
        <label>Job Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mavensmate/Mobile/src/classes/MobileJobsController.cls
public with sharing class MobileJobsController {

	private string jobs;
	private string parts;

	public MobileJobsController() {
		List<Job__c> jobList = [SELECT Id, Name, Status__c FROM Job__c WHERE Status__c='Open'];	
		List<Job_Part__c> partList = [SELECT Id, Name FROM Job_Part__C WHERE Job__r.Name = '2249'];

		 jobs = JSON.serialize(jobList);
		 //parts = JSON.serialize(partList);
        system.debug('Jobs as JSON: ' + jobs);	
	}

public string getParts(){
		return parts;
	}

	public string getJobs(){
		return jobs;
	}
}